apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: anime-api-service
  newName: ghcr.io/katerynakunieva/anime-spring-rest-api
  newTag: latest
- name: email-service
  newName: ghcr.io/katerynakunieva/email-service-rabbitmq-elasticsearch
  newTag: latest
- name: email-service-service
  newName: ghcr.io/katerynakunieva/email-service-rabbitmq-elasticsearch
  newTag: latest
- name: episode-api-service
  newName: ghcr.io/katerynakunieva/anime-node-js-rest-api
  newTag: latest
- name: frontend-service
  newName: ghcr.io/katerynakunieva/anime-react-redux-app
  newTag: a787b246e4a72895d8b6fff716dfd18baf3f6c6e
- name: gateway-service
  newName: ghcr.io/katerynakunieva/anime-oauth-gateway
  newTag: 59ea7ae8ef3538bb993be649f115d7cdb3ce9518
