apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: anime-api-service
  newName: ghcr.io/katerynakunieva/anime-spring-rest-api
  newTag: d412d423ec0c417896128cc265fc70c0827c8a5d
- name: email-service
  newName: ghcr.io/kunievakateryna/email-service-rabbitmq-elasticsearch
  newTag: latest
- name: email-service-service
  newName: ghcr.io/katerynakunieva/email-service-rabbitmq-elasticsearch
  newTag: latest
- name: episode-api-service
  newName: ghcr.io/katerynakunieva/anime-node-js-rest-api
  newTag: latest
- name: frontend-service
  newName: ghcr.io/katerynakunieva/anime-react-redux-app
  newTag: latest
