apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anime-project

resources:
  # Namespace
  - namespace.yml

  # Infrastructure
  - postgresql
  - mongodb
  - elasticsearch 
  - rabbitmq
  - mailhog

  # Gateway
  - oauth-gateway

  # Services
  - anime-api
  - episode-api
  - email-service
  - frontend

  # Ingress (external access)
  - ingress